- name: Apply roles for Infra group
  hosts: all
  become: true
  connection: local

  vars:
  custom_roles:
    - common
    - docker
    - cloudwatch
    - codedeploy

  tasks:
    - name: Include roles dynamically
      include_role:
        name: "{{ item }}"
      loop: "{{ custom_roles }}"
