- name: Apply roles for server group
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Include roles dynamically
      include_role:
        name: "{{ item }}"
      loop: "{{ custom_roles }}"