- name: Apply roles for server group
  hosts: localhost
  become: true

  vars:
    custom_roles:
      - common
      - docker
      - codedeploy
      - cloudwatch

  tasks:
    - name: Include roles dynamically
      include_role:
        name: "{{ item }}"
      loop: "{{ custom_roles }}"

